# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: MASTS Numerical and Experimental Hydrodynamic Modelling Forum
subtitle: Modelling of Scottish Coastal Waters: A Roadmap
email: rory.murray@gov.scot
description: >- # this means to ignore newlines until "baseurl:"
  Our oceans provide many life-sustaining benefits to coastal communities, including food, water, energy and employment, as well as affecting our weather and climate, including providing a sink for excess heat and carbon in the atmosphere. Management of the marine environment should consider many factors. Sustainable management of marine resources is central, as is stewardship of Scottish Coastal waters for future generations. A number of industries and communities need to co-exist. The environment, industries and communities need to be resilient to climate change and other shocks. Scottish coastal areas should be prosperous and content. Therefore, many pressures and outcomes must be considered in planning and projecting possible futures. Modelling can be a key tool in those projections.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://masts-nehm.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
